/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFACES;

import CONTROLADOR.Conexion;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ABEL
 */
public class REGISTRO_ASISTENCIA_PERSONAL extends javax.swing.JFrame {
Conexion cc = new Conexion();
    Connection cn = (Connection) cc.Conexion();
    private boolean ban=true;
    /**
     * Creates new form REGISTRO_ASISTENCIA_PERSONAL
     */
    public REGISTRO_ASISTENCIA_PERSONAL() {
        initComponents();
         Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = getSize();
        setLocation((pantalla.width - ventana.width) / 2,
                (pantalla.height - ventana.height) / 2);
         Hora hora = new Hora();
         ban=true;
hora.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usu = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_registrar = new javax.swing.JButton();
        lb_hora = new javax.swing.JLabel();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO DE ASISTENCIA");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("REGISTRO DE ASISTENCIA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_registrar.setBackground(new java.awt.Color(204, 255, 204));
        btn_registrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_registrar.setText("REGISTRAR");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        lb_hora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_hora.setText("jLabel4");

        label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label.setText("HORA:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_hora)
                    .addComponent(label))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        // TODO add your handling code here:
        String SQL = "";

                 SQL="SELECT * FROM usuario WHERE USU_usuario='"+usu.getText()+"'AND USU_contraseña="+pass.getText();   
          String c="";
          try {
            Statement st = cn.createStatement();
            ResultSet rs=st.executeQuery(SQL);
            while(rs.next())
            {              
                 c=rs.getString(5); 
            }
     if(!c.equalsIgnoreCase("")){
        ////////////////////////////////////////////insercion en tabla horario
        
      String[] dias={"Domingo","Lunes","Martes", "Miércoles","Jueves","Viernes","Sábado"};
        Date hoy=new Date();
      int numeroDia=0;
      Calendar cal= Calendar.getInstance();
      cal.setTime(hoy);
      numeroDia=cal.get(Calendar.DAY_OF_WEEK);
      System.out.println("hoy es "+ dias[numeroDia - 1]+" numero: "+numeroDia);
    int[] dias_numero={7,1,2,3,4,5,6};
      ///////////////////////////////////////////////////
      st.close();
      rs.close();
      /////////////////////////////fecha para observacion
      Calendar c1 = Calendar.getInstance();
        String dia = Integer.toString(c1.get(Calendar.DATE));
        String mes = Integer.toString(c1.get(Calendar.MONTH)+1);
        String anio = Integer.toString(c1.get(Calendar.YEAR));
        if(mes.length()==1){
         mes="0"+mes;   
        }
         System.out.println("fecha: "+anio+"/"+mes+"/"+dia);
      /////////////////////////////
      
         SQL="SELECT * FROM detalle_horario";
         int con=0;
         Statement st2 = cn.createStatement();
            ResultSet rs2=st2.executeQuery(SQL);
            while(rs2.next())
            {              
                 con++;
            }
            st2.close();
            rs2.close();
            ////////////////////////////
            String f=dia+"/"+mes+"/"+anio;
            SQL="SELECT * FROM detalle_horario WHERE EMPLEADOS_EMPL_dni='"+c+"' AND DETALL_HOR_observacion='"+f+"'";   
            int ban_salida=0;
         Statement stt = cn.createStatement();
            ResultSet rst=stt.executeQuery(SQL);
             
            while(rst.next())
            {              
                 ban_salida=rst.getInt(1); 
                 System.out.println("id: "+ban_salida);
            }
            stt.close();
            rst.close();
            ////////////////////////////
            System.out.println("contador:  "+con);
             String sql="INSERT INTO detalle_horario (DETALL_HOR_id,DETALL_HOR_Hingreso,DETALL_HOR_Hsalida,DETALL_HOR_observacion,EMPLEADOS_EMPL_dni,HORARIO_HORARIO_id)" +"VALUES (?,?,?,?,?,?)";
            PreparedStatement pst = cn.prepareStatement(sql);
                
                pst.setInt(1, con+1);
                pst.setString(2,lb_hora.getText() );
                pst.setString(3,"");
                pst.setString(4, dia+"/"+mes+"/"+anio);
                pst.setString(5, c);
                pst.setString(6, ""+dias_numero[numeroDia-1]);
               
               
                
                if(ban_salida!=0){
                    /////////////////////////////////conprobando que no haya registrado salida antes
                    f=dia+"/"+mes+"/"+anio;
            SQL="SELECT * FROM detalle_horario WHERE EMPLEADOS_EMPL_dni='"+c+"' AND DETALL_HOR_observacion='"+f+"'";   
            String ban_salida2="";
         Statement stt2 = cn.createStatement();
            ResultSet rst2=stt2.executeQuery(SQL);
             
            while(rst2.next())
            {              
                 ban_salida2=rst2.getString(3); 
                 System.out.println("hora_salida: "+ban_salida2);
            }
            stt2.close();
            rst2.close();
                    /////////////////////////////////
                    if(ban_salida2.equalsIgnoreCase("")){
                    String sql2="UPDATE detalle_horario SET DETALL_HOR_Hsalida = ? WHERE DETALL_HOR_id ='"+ban_salida+"'";
            PreparedStatement pst2 = cn.prepareStatement(sql2);
              pst2.setString(1,lb_hora.getText());


   
                pst2.executeUpdate();
                   pst2.close();
                    JOptionPane.showMessageDialog(null,"REGISTRO EXITOSO!!!","AVISO",1);
                    }else{
                    JOptionPane.showMessageDialog(null,"YA SE REGISTRO SALIDA!!!","AVISO",1);
                    }
                }else{
                     JOptionPane.showMessageDialog(null,"REGISTRO EXITOSO!!!","AVISO",1);
                pst.executeUpdate();
                pst.close();
                }
                

                 
                
         ///////////////////////////////////////
     }
             } catch (SQLException ex) {
           Logger.getLogger(Ingreso_Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_registrarActionPerformed
    public class Hora extends Thread{
  public void run(){
   while(ban==true){
   
       try {
           Calendar calendario = Calendar.getInstance();
           int hora, minutos, segundos;
           hora =calendario.get(Calendar.HOUR_OF_DAY);
           minutos = calendario.get(Calendar.MINUTE);
           segundos = calendario.get(Calendar.SECOND);
           lb_hora.setText(hora+":"+minutos+":"+segundos);
           sleep(1000);
       } catch (InterruptedException ex) {
           Logger.getLogger(REGISTRO_ASISTENCIA_PERSONAL.class.getName()).log(Level.SEVERE, null, ex);
       }
   }
  }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REGISTRO_ASISTENCIA_PERSONAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REGISTRO_ASISTENCIA_PERSONAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REGISTRO_ASISTENCIA_PERSONAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REGISTRO_ASISTENCIA_PERSONAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REGISTRO_ASISTENCIA_PERSONAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lb_hora;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField usu;
    // End of variables declaration//GEN-END:variables
}
